name: CI/CD Docker Compose (Master-only)

on:
  push:
    branches:
      - master    

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_KEY: ${{ secrets.EC2_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2 Deploy to EC2
      - name: SSH and deploy master
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            cd ~/Models-Monitor
            echo "Checking out master branch"
            git fetch --all
            git checkout master
            git pull origin master

            echo "Stopping current stack"
            docker compose -f docker-compose.master.yml down

            echo "Starting updated stack"
            docker compose -f docker-compose.master.yml up -d --build
